# Generated by Django 4.0.4 on 2022-05-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_country_country_o'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_o',
            old_name='name',
            new_name='country',
        ),
    ]
