# Generated by Django 4.0.4 on 2022-05-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_name_country_o_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_o',
            old_name='language',
            new_name='languages',
        ),
    ]
